apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: default
spec:
  project: default

  source: 
    repoURL: git@github.com/jojoskittlez/argocd-example-apps.git
    targetRevision: HEAD
    path: main

  destination:
    server: https://api.xbd1mu1p2c.jwulf.projects.stage.gardener.get-cloud.io
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace = true
    automated: 
      selfHeal: true
      prune: true





