apiVersion: v1
kind: Application
metadata:
  name: nginx
  namespace: default
spec:
  project: default

  source: 
    repoURL: git@github.com:jojoskittlez/argocd-example-apps.git
    targetRevision: HEAD
    path: test

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated: 
      selfHeal: true
      prune: true





